version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: majornick
      POSTGRES_PASSWORD: majornick
    ports:
      - "54321:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  backend-microservice:
    build:
      context: ./backend/notifications
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notifications
      SPRING_DATASOURCE_USERNAME: majornick
      SPRING_DATASOURCE_PASSWORD: majornick
  ui_microservice:
    build:
      context: ./client/notificationUIclient
      dockerfile: Dockerfile
    ports:
      - "8000:8090"
    depends_on:
      - backend-microservice
    environment:
      BACKEND_MICROSERVICE_URL: http://backend-microservice:8080
      SERVER_PORT: 8090